// Download Manager – NewPipe birebir
// video / audio / caption ayrı seç

import * as FileSystem from 'expo-file-system';
import { saveLocalConfig, loadLocalConfig } from './config';

export type DownloadJob = {
  id: string;
  videoId: string;
  title: string;
  type: 'video' | 'audio' | 'caption';
  quality: string;
  url: string;
  status: 'queued' | 'downloading' | 'done' | 'error';
  progress: number;
  localUri?: string;
  createdAt: number;
};

const DL_KEY = 'dl_jobs';

async function getJobs(): Promise<DownloadJob[]> {
  return (await loadLocalConfig<DownloadJob[]>(DL_KEY)) || [];
}
async function saveJobs(jobs: DownloadJob[]) {
  await saveLocalConfig(DL_KEY, jobs);
}

export async function queueDownload(job: Omit<DownloadJob, 'status'|'progress'|'createdAt'>) {
  const jobs = await getJobs();
  const full: DownloadJob = { ...job, status: 'queued', progress: 0, createdAt: Date.now() };
  jobs.unshift(full);
  await saveJobs(jobs);
  // hemen başlat – NewPipe paralel 1
  startNext();
  return full;
}

let running = false;
async function startNext() {
  if (running) return;
  const jobs = await getJobs();
  const next = jobs.find(j => j.status === 'queued');
  if (!next) return;
  running = true;
  next.status = 'downloading';
  await saveJobs(jobs);

  try {
    const ext = next.type === 'audio' ? 'm4a' : next.type === 'caption' ? 'vtt' : 'mp4';
    const filename = `${next.videoId}_${next.quality}.${ext}`.replace(/[^a-zA-Z0-9_.-]/g,'_');
    const target = FileSystem.documentDirectory + 'tubenest/' + filename;

    await FileSystem.makeDirectoryAsync(FileSystem.documentDirectory + 'tubenest', { intermediates: true }).catch(()=>{});

    const dl = FileSystem.createDownloadResumable(
      next.url,
      target,
      {},
      (p) => {
        next.progress = p.totalBytesWritten / (p.totalBytesExpectedToWrite || 1);
        // throttle save
      }
    );
    const res = await dl.downloadAsync();
    next.status = 'done';
    next.progress = 1;
    next.localUri = res?.uri;
  } catch (e) {
    next.status = 'error';
  }
  await saveJobs(jobs);
  running = false;
  startNext();
}

export async function listDownloads() { return getJobs(); }
export async function removeDownload(id: string) {
  const jobs = (await getJobs()).filter(j => j.id !== id);
  await saveJobs(jobs);
}

// NewPipe: Set title, choose video/audio/caption, select format, resolution
export function buildDownloadOptions(streamInfo: any) {
  const video = streamInfo.videoStreams?.map((v:any)=>({
    label: `${v.height || v.quality}p • ${v.format?.split(';')[0]}`,
    url: v.url, quality: String(v.height||v.quality), type:'video' as const
  })) || [];
  const audio = streamInfo.audioStreams?.map((a:any)=>({
    label: `Audio ${Math.round((a.bitrate||128000)/1000)}kbps • ${a.format?.split(';')[0]}`,
    url: a.url, quality: 'audio', type:'audio' as const
  })) || [];
  const captions = streamInfo.subtitles?.map((c:any)=>({
    label: `Caption ${c.language}${c.autoGenerated?' (auto)':''}`,
    url: c.url, quality: c.language, type:'caption' as const
  })) || [];
  return [...video, ...audio, ...captions];
}
