// Extractor katmanı ayrı module – madde 4
// 1. madde: şu an sadece YT, ileride farklı platformlar eklenebilir

import { StreamInfo, ServiceId, StreamingService } from './types';
import { YoutubeService, getStreamInfo as ytGet } from './youtube';
import { getFlag } from '../featureFlags';
import { reportError } from '../errorReporter';

// Service registry – NewPipe ServiceList.java mantığı
const SERVICES: Record<ServiceId, StreamingService | null> = {
  youtube: new YoutubeService(),
  peertube: null,   // ileride eklenecek – 1. madde
  soundcloud: null,
  bandcamp: null,
  ccc: null,
};

export function getService(id: ServiceId): StreamingService | null {
  return SERVICES[id];
}

export function listEnabledServices(): ServiceId[] {
  return (Object.keys(SERVICES) as ServiceId[]).filter(s => SERVICES[s] !== null);
}

// NewPipeExtractor fallback chain
export async function extractStreamUniversal(urlOrId: string, preferredService: ServiceId = 'youtube'): Promise<StreamInfo> {
  const attempts: Array<() => Promise<StreamInfo>> = [];

  if (preferredService === 'youtube' && getFlag('extractor_youtube_innertube')) {
    attempts.push(() => ytGet(urlOrId));
  }

  if (getFlag('extractor_youtube_piped_fallback')) {
    attempts.push(async () => {
      // Piped API – NewPipe 403 fix karşılığı
      const id = urlOrId.includes('http') ? extractId(urlOrId) : urlOrId;
      const r = await fetch(`https://pipedapi.kavin.rocks/streams/${id}`);
      if (!r.ok) throw new Error('piped failed ' + r.status);
      const j = await r.json();
      return mapPipedToStreamInfo(j, id);
    });
  }

  // 3. fallback: Invidious
  attempts.push(async () => {
    const id = urlOrId.includes('http') ? extractId(urlOrId) : urlOrId;
    const r = await fetch(`https://inv.nadeko.net/api/v1/videos/${id}`);
    const j = await r.json();
    return mapInvidiousToStreamInfo(j, id);
  });

  let lastErr: any;
  for (const fn of attempts) {
    try {
      return await fn();
    } catch (e) {
      lastErr = e;
      await reportError('extractStreamUniversal', e, { extractor: preferredService, url: urlOrId });
      continue;
    }
  }
  throw lastErr || new Error('All extractors failed');
}

function extractId(u: string) {
  try {
    const url = new URL(u);
    return url.searchParams.get('v') || url.pathname.slice(1);
  } catch { return u; }
}

function mapPipedToStreamInfo(j: any, id: string): StreamInfo {
  return {
    id,
    serviceId: 'youtube',
    title: j.title,
    uploader: j.uploader,
    uploaderUrl: j.uploaderUrl,
    uploaderAvatar: j.uploaderAvatar,
    viewCount: String(j.views),
    description: j.description,
    thumbnails: j.thumbnailUrl ? [j.thumbnailUrl] : [],
    duration: j.duration,
    videoStreams: (j.videoStreams || []).map((v:any)=>({
      url: v.url, format: v.format, quality: v.quality, bitrate: v.bitrate || 0,
      width: parseInt(v.quality), height: 0, isVideo: true, isAudio: false
    })),
    audioStreams: (j.audioStreams || []).map((a:any)=>({
      url: a.url, format: a.format, quality: a.quality, bitrate: a.bitrate || 0,
      isVideo: false, isAudio: true
    })),
    hlsUrl: j.hls,
    subtitles: (j.subtitles || []).map((s:any)=>({
      url: s.url, language: s.code, autoGenerated: s.autoGenerated, format: 'vtt'
    }))
  };
}

function mapInvidiousToStreamInfo(j: any, id: string): StreamInfo {
  return {
    id,
    serviceId: 'youtube',
    title: j.title,
    uploader: j.author,
    uploaderUrl: 'https://www.youtube.com/channel/' + j.authorId,
    viewCount: String(j.viewCount),
    likeCount: j.likeCount,
    description: j.description,
    thumbnails: j.videoThumbnails?.map((t:any)=>t.url) || [],
    duration: j.lengthSeconds,
    videoStreams: j.formatStreams?.map((f:any)=>({
      url: f.url, format: f.type, quality: f.qualityLabel, bitrate: 0,
      width: f.width, height: f.height, fps: f.fps,
      isVideo: true, isAudio: true
    })) || [],
    audioStreams: j.adaptiveFormats?.filter((f:any)=>f.type?.includes('audio')).map((f:any)=>({
      url: f.url, format: f.type, quality: f.quality, bitrate: f.bitrate || 0,
      isVideo: false, isAudio: true
    })) || [],
    hlsUrl: j.hlsUrl,
    subtitles: j.captions?.map((c:any)=>({
      url: c.url, language: c.languageCode, autoGenerated: false, format: 'vtt'
    })) || []
  };
}

// Platform eklentisi için – 1. madde
export async function registerService(serviceId: ServiceId, service: StreamingService) {
  (SERVICES as any)[serviceId] = service;
}
