// NewPipe Extractor pattern – TypeScript port
// Extractor katmanı ayrı module – madde 4

export interface LinkHandler {
  url: string;
  id: string;
  serviceId: ServiceId;
}

export type ServiceId = 'youtube' | 'peertube' | 'soundcloud' | 'bandcamp' | 'ccc';

export interface StreamInfo {
  id: string;
  serviceId: ServiceId;
  title: string;
  uploader: string;
  uploaderUrl: string;
  uploaderAvatar?: string;
  viewCount: string;
  likeCount?: number;
  description: string;
  thumbnails: string[];
  duration: number;
  uploadDate?: string;
  // NewPipe: getVideoStreams / getAudioStreams
  videoStreams: MediaStream[];
  audioStreams: MediaStream[];
  hlsUrl?: string;
  dashMpd?: string;
  subtitles: CaptionTrack[];
}

export interface MediaStream {
  url: string;
  format: string;
  quality: string;
  bitrate: number;
  codec?: string;
  width?: number;
  height?: number;
  fps?: number;
  isVideo: boolean;
  isAudio: boolean;
}

export interface CaptionTrack {
  url: string;
  language: string;
  autoGenerated: boolean;
  format: 'vtt' | 'ttml' | 'srt';
}

export interface Extractor<T> {
  serviceId: ServiceId;
  fetchPage(linkHandler: LinkHandler): Promise<void>;
  getInfo(): Promise<T>;
}

export interface StreamingService {
  serviceId: ServiceId;
  getName(): string;
  getStreamExtractor(id: string): Extractor<StreamInfo>;
  getSearchExtractor(query: string): any;
  getChannelExtractor(channelId: string): any;
}

// NewPipe: Info / InfoItem collector
export interface InfoItem {
  serviceId: ServiceId;
  id: string;
  title: string;
  url: string;
  thumbnails: string[];
}
