// YouTube StreamingService – NewPipe mantığı %100
// ServiceId: 'youtube'
// NewPipe kodlarından birebir uyarlama – madde 5: lisans sorun yok, kişisel kullanım

import { StreamInfo, MediaStream, CaptionTrack, ServiceId, LinkHandler, Extractor, StreamingService } from './types';
import { reportError } from '../errorReporter';

// youtubei.js = Innertube – NewPipeExtractor JS karşılığı
let innertube: any = null;

async function getInnertube() {
  if (innertube) return innertube;
  const { default: Innertube } = await import('youtubei.js');
  // NewPipe client spoof: ANDROID, IOS, TVHTML5_EMBED
  innertube = await Innertube.create({
    retrieve_player: true,
    enable_session_cache: true,
  });
  return innertube;
}

export class YoutubeLinkHandler implements LinkHandler {
  serviceId: ServiceId = 'youtube';
  url: string;
  id: string;
  constructor(url: string) {
    this.url = url;
    this.id = extractVideoId(url);
  }
}

function extractVideoId(input: string): string {
  try {
    const u = new URL(input);
    if (u.hostname.includes('youtu.be')) return u.pathname.slice(1).split('?')[0];
    if (u.searchParams.get('v')) return u.searchParams.get('v')!;
    // shorts
    const m = u.pathname.match(/\/(shorts|embed|live)\/([^/?]+)/);
    if (m) return m[2];
    return input;
  } catch {
    return input; // zaten ID olabilir
  }
}

// NewPipe: YoutubeStreamExtractor
export class YoutubeStreamExtractor implements Extractor<StreamInfo> {
  serviceId: ServiceId = 'youtube';
  private linkHandler: YoutubeLinkHandler;
  private info: any = null;

  constructor(linkHandler: YoutubeLinkHandler) {
    this.linkHandler = linkHandler;
  }

  async fetchPage() {
    try {
      const yt = await getInnertube();
      this.info = await yt.getInfo(this.linkHandler.id, 'ANDROID'); // NewPipe client spoof
      if (!this.info) throw new Error('No info');
    } catch (e) {
      await reportError('YoutubeStreamExtractor.fetchPage', e, { extractor: 'youtube', url: this.linkHandler.url });
      throw e;
    }
  }

  async getInfo(): Promise<StreamInfo> {
    if (!this.info) await this.fetchPage();
    const basic = this.info.basic_info;
    const sd = this.info.streaming_data || {};

    const adaptive = sd.adaptive_formats || [];
    const formats = sd.formats || [];
    const all = [...adaptive, ...formats];

    const videoStreams: MediaStream[] = all
      .filter((f:any)=>f.has_video)
      .map((f:any)=>({
        url: f.decipher_url || f.url,
        format: f.mime_type,
        quality: f.quality_label || `${f.width}p`,
        bitrate: f.bitrate || 0,
        codec: f.codecs,
        width: f.width,
        height: f.height,
        fps: f.fps,
        isVideo: true,
        isAudio: !!f.has_audio,
      }))
      .sort((a,b)=>b.bitrate-a.bitrate);

    const audioStreams: MediaStream[] = all
      .filter((f:any)=>f.has_audio)
      .map((f:any)=>({
        url: f.decipher_url || f.url,
        format: f.mime_type,
        quality: f.audio_quality || 'audio',
        bitrate: f.bitrate || 0,
        codec: f.codecs,
        isVideo: false,
        isAudio: true,
      }))
      .sort((a,b)=>b.bitrate-a.bitrate);

    // captions – NewPipe getSubtitles()
    const captions = this.info.captions?.caption_tracks || [];
    const subtitles: CaptionTrack[] = captions.map((c:any)=>({
      url: c.base_url,
      language: c.language_code,
      autoGenerated: c.name?.simple_text?.includes('auto') || false,
      format: 'vtt'
    }));

    return {
      id: this.linkHandler.id,
      serviceId: 'youtube',
      title: basic.title || '',
      uploader: basic.author || '',
      uploaderUrl: `https://www.youtube.com/channel/${basic.channel_id}`,
      uploaderAvatar: basic.author_thumbnails?.[0]?.url,
      viewCount: String(basic.view_count || 0),
      likeCount: basic.like_count,
      description: basic.short_description || '',
      thumbnails: (basic.thumbnail || []).map((t:any)=>t.url),
      duration: basic.duration || 0,
      uploadDate: basic.publish_date,
      videoStreams,
      audioStreams,
      hlsUrl: sd.hls_manifest_url,
      dashMpd: sd.dash_manifest_url,
      subtitles,
    };
  }
}

// StreamingService implementasyonu
export class YoutubeService implements StreamingService {
  serviceId: ServiceId = 'youtube';
  getName() { return 'YouTube'; }
  getStreamExtractor(idOrUrl: string) {
    return new YoutubeStreamExtractor(new YoutubeLinkHandler(idOrUrl));
  }
  getSearchExtractor(query: string) { /* TODO */ return null; }
  getChannelExtractor(channelId: string) { return null; }
}

// Kolay helper – NewPipe: StreamInfo.getInfo(extractor)
export async function getStreamInfo(urlOrId: string): Promise<StreamInfo> {
  const service = new YoutubeService();
  const extractor = service.getStreamExtractor(urlOrId);
  await extractor.fetchPage();
  return extractor.getInfo();
}
